### ISSUE TITLE
请教问题 letta创建代理时错误

### ISSUE THREAD

**Issue by SMXG-rbq** [Zao-chen/ZcChat#12]
![QQ图片20241221022003](https://github.com/user-attachments/assets/d7d67ebc-3814-4c6a-b389-b3ed2956b7de)
![QQ图片20241221022008](https://github.com/user-attachments/assets/1df70a0c-0901-4531-a1e7-9eabc0a3ceaf)

**Comment by fallingmeteorite** [comment]
@SMXG-rbq 使用旧的版本而不是新的，你应该使用letta-0.5.5

**Comment by SMXG-rbq** [comment]
> @SMXG-rbq 使用旧的版本而不是新的，你应该使用letta-0.5.5

好的谢谢

**Comment by Zao-chen** [comment]
新版本我测下来也有一些有一些bug，等稳定了再去用

**Comment by Zao-chen** [comment]
已支持新版本letta
