### ISSUE TITLE
模型在屏幕之外，无法移动

### ISSUE THREAD

**Issue by lishufood** [Zao-chen/ZcChat#13]
移动模型的方法目前只有拖拽，如果模型在屏幕之外，就无法移动。
开始用2个屏幕，拖拽到副屏，然后使用1个屏幕，即可复现此现象。

希望作者可以添加手动修改模型坐标的能力，或者提供一个复原的功能

**Comment by Zao-chen** [comment]
你可以在setting.ini中手动修改。当然后续会更新。
