### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by julescules** [Zao-chen/ZcChat#18]
大佬，为什么我的letta页面和你的不一样，没有那个letta templates,而且配完后，对话说出现不知名错误

**Comment by Zao-chen** [comment]
能否提供报错信息，letta命令行应该会有报错

**Comment by julescules** [comment]
这个报错信息要怎么看，模式是默认的

**Comment by julescules** [comment]
版本是Letta-0.6.6

**Comment by julescules** [comment]
打开Letta server命令后是这样的，(sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/20/e3q8)
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Existing SQLite DB schema is invalid, and schema migrations are not supported for SQLite. To have migrations        │
│ supported between Letta versions, please run Letta with Docker (https://docs.letta.com/server/docker) or use        │
│ Postgres by setting LETTA_PG_URI.                                                                                   │
│                                                                                                                     │
│ If you wish to keep using SQLite, you can reset your database by removing the DB file with rm ~/.letta/sqlite.db or │
│ downgrade to your previous version of Letta.

**Comment by julescules** [comment]
我删了重来了

**Comment by julescules** [comment]
![Uploading 屏幕截图 2024-12-24 200102.png…]()

**Comment by julescules** [comment]
网页是这样子的

**Comment by julescules** [comment]
[Uploading 屏幕截图 2024-12-24 200102.png…]()

**Comment by Zao-chen** [comment]
尝试刚刚更新的1.2.2

**Comment by julescules** [comment]
![image](https://github.com/user-attachments/assets/e947a700-b0d0-4b95-9a3a-bac5b241f4f2)

**Comment by julescules** [comment]
这个选哪个来创建

**Comment by Zao-chen** [comment]
> 这个选哪个来创建

按照自己需求即可，一般第一个就行了

**Comment by julescules** [comment]
好

**Comment by julescules** [comment]
![image](https://github.com/user-attachments/assets/8d64f4e4-9bb3-44cc-a078-38dcd598aab6)

**Comment by julescules** [comment]
还是这样

**Comment by Zao-chen** [comment]
> 还是这样

看下新的readme，letta链接应该是lettaserver启动时候命令行输出的那个链接

**Comment by julescules** [comment]
这个链接http://localhost:8283/进去后，让我用新的IDE

**Comment by julescules** [comment]
readme 在哪看

**Comment by julescules** [comment]
现在好了，但语音还是不行

**Comment by julescules** [comment]
![image](https://github.com/user-attachments/assets/b8173a86-233e-487b-a6bf-6b2609755b2e)

**Comment by julescules** [comment]
现在好了，这些网页可以吗

**Comment by julescules** [comment]
这些网页可以关吗

**Comment by julescules** [comment]
关了还能运行吗？

**Comment by julescules** [comment]
谢谢大佬

**Comment by Zao-chen** [comment]
> 这些网页可以关吗

所有网页都是可以关闭的，只要命令行在就行
