### ISSUE TITLE
letta server这一步没办法继续进行

### ISSUE THREAD

**Issue by WebTsing** [Zao-chen/ZcChat#6]
Up你好，我是这学期才开始接触python的，目前只有一点点的基础。目前已经完成的就只有下载和pip install，完全按照视频里面的步骤。
完成以上工作后在我尝试输入letta server时出现了这个情况。可以帮我看看这是什么情况吗，谢谢。
![image](https://github.com/user-attachments/assets/5928b3b4-f55e-46e1-ace0-18c4c152c362)

**Comment by Zao-chen** [comment]
看最后的黄字，你需要把他添加进环境变量。

**Comment by WebTsing** [comment]
> 看最后的黄字，你需要把他添加进环境变量。
谢谢！

**Comment by WebTsing** [comment]
Btw，我现在下载了一个gemma的模型，但是我看到zcChat里面只能选letta。有什么办法可以接我下载的新模型吗。

**Comment by Zao-chen** [comment]
letta并不是模型，而是代理。看下下面这图。![letta_overview.png](https://github.com/user-attachments/assets/3eddd35f-5765-4122-91f0-eb292561b705)
所以说你可以通过letta连接gemini，下面是连接gemini[文档](https://docs.letta.com/models/google)

**Comment by WebTsing** [comment]
> letta并不是模型，而是代理。看下下面这图。![letta_overview.png](https://private-user-images.githubusercontent.com/77674075/395742820-3eddd35f-5765-4122-91f0-eb292561b705.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxNTA1ODYsIm5iZiI6MTczNDE1MDI4NiwicGF0aCI6Ii83NzY3NDA3NS8zOTU3NDI4MjAtM2VkZGQzNWYtNTc2NS00MTIyLTkxZjAtZWIyOTI1NjFiNzA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE0VDA0MjQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyNDJmZjg3NmQxYzRhZTliZGU4YTg4NTFhZTk0MWFhOWViZTBmNmI0ZjRmOTE3YzYwODEyYWRjZWYxOTY0MmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6oUN2HyIPynb8lpa6CtVVHnaVwZPiL7tYcBJ-SdHQfo) 所以说你可以通过letta连接其他模型，下面是连接[文档](https://docs.letta.com/models/openai)

不好意思我知道的有点太少了，目前学的东西都跟ai不沾边。谢谢啦～
